version: 2
jobs:
  build:  # required for runs that don't use workflows
    working_directory: ~/ptf
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout  # checkout source code to working directory
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |  # use pipenv to install dependencies
            sudo pip install --upgrade pip
            sudo pip install pipenv
            pipenv install
            sudo ./ptf | use modules/exploitation/install_update_all  
            sudo ./ptf | exit 
            sudo ./ptf | exit
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
